import Head from "next/head";
import Image from "next/image";
import H1 from "@/components/H1";
import MyResources from "@/components/MyResources";
import { DataStore, withSSRContext } from "aws-amplify";
import { Resources, ResourcesCategory, Category } from "@/models";
import { serializeModel } from "@aws-amplify/datastore/ssr";
import Layout from "@/components/Layout";
import MyAuth from "@/components/MyAuth";

export async function getServerSideProps() {
  const { DataStore } = withSSRContext();
  const resourceList = await DataStore.query(Resources);
  const resourceCategories = await DataStore.query(ResourcesCategory);
  const categoryIdsSet = new Set(resourceCategories.map((pc) => pc.categoryId));
  const categoryIds = [...categoryIdsSet];

  const cachedCategories = {};

  const categories = await Promise.all(
    categoryIds.map(async (categoryId) => {
      if (cachedCategories[categoryId]) {
        return [cachedCategories[categoryId]];
      } else {
        const category = await DataStore.query(Category, categoryId);
        cachedCategories[categoryId] = category;
        return category;
      }
    })
  );

  return {
    props: {
      resourceList: serializeModel(resourceList),
      categories: serializeModel(categories),
      resourceCategories: serializeModel(resourceCategories),
    },
  };
}

const FreeResources = ({ resourceList, categories, resourceCategories }) => {
  console.log(resourceList, categories, resourceCategories);

  return (
    // <MyAuth>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center">
        <Layout>
          <H1>Descarga contenido exclusivo gratis.</H1>
          <MyResources
            resourceList={resourceList}
            categories={categories}
            resourceCategories={resourceCategories}
          />
        </Layout>
        
      </main>
      </>
    // </MyAuth>
  );
};

export default FreeResources;
