import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import MyNavBar from '@/components/MyNavBar'
import HeroResponsive from '@/components/HeroResponsive'
import MyColleges from '@/components/MyColleges'
import H1 from '@/components/H1'
import MyCallToAction from '@/components/MyCallToAction'
import MyProductFeatures from '@/components/MyProductFeatures'
import MyFooter from '@/components/MyFooter'
import MyTestimonials from '@/components/MyTestimonials'
import MyHeroResponsive2 from '@/ui-components/MyHeroResponsive2'
import { withSSRContext } from 'aws-amplify'
import { Colleges, Testimonials } from '@/models'
import { serializeModel } from '@aws-amplify/datastore/ssr';

export async function getServerSideProps() {
  const { DataStore } = withSSRContext();
  const collegesList = await DataStore.query(Colleges);
  return {
    props: {
      collegesList: serializeModel(collegesList),
    },
  };
}

const inter = Inter({ subsets: ['latin'] })

export default function Home({collegesList}) {
  return (
    <>
      <Head>
        <title>Kids Tutor Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ textAlign: '-webkit-center' }} className='' >
        <MyNavBar />
        <HeroResponsive />
        <H1>Colegios que usan nuestros métodos y productos de aprendizaje.</H1>
        <MyColleges collegesList={collegesList}/>
        <MyCallToAction
          mainText={'Alto Nivel Academico, gracias a la labor conjunta basada en resultados con nuestro equipo de expertos.'}
          buttonLabel={'Integra tu Colegio Ahora'}
        />
        <MyProductFeatures />
        <H1>¿Quieres saber cómo mejorar la educación de tus pequeños? Nuestros clientes satisfechos tienen historias que compartir.</H1>
        <MyTestimonials />
        <MyFooter />
      </main>
    </>
  )
}
