/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sugefl6kdzch3kj5ensfin6tsy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.APPSYNC_APP_KEY,
    "aws_cognito_identity_pool_id": "us-east-1:b21f97d8-4e5b-4fdd-a757-39cfb1d3cb9f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_elZ6f5T0H",
    "aws_user_pools_web_client_id": "1o4igpbtrqnn3ngfrtmdmk9c2m",
    "oauth": {
        "domain": "ptslaimxuxy5-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.kidstutor.co/",
        "redirectSignOut": "https://www.kidstutor.co/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "my-store-ct-storage-aabd6fd7195834-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
